name = "cinnatastic"
author = "wawwior"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9dfbf08e14f6fe68e4e3663ea91c5f00ee9ac28683d6b906162d320007595673"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
