name = "cinnatastic"
author = "wawwior"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f61bb937d5a6a66b3b2901f72caf2fa86bf092387b1cd97cadfba464a5651a0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
