name = "cinnatastic"
author = "wawwior"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2756d2885635db1aefb90aebf1025193a76c5ae81e4a01d4716b0e59fa5fe846"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
