[general]
	#
	#How dynamic assets are generated. If cached the cache will regenerate once any mod or pack changes
	#- NEVER: This mod will never attempt to generate the cache folder. The assets will be put in memory
	#- RUN_ONCE: Will generate once & the assets will be stored in memory every time you launched.
	#- CACHED: create a CACHE folder via .minecraft/dynamic-resource-pack-cache
	#- CACHED_ZIPPED: create a ZIP folder via .minecraft/dynamic-resource-pack-cache
	#- ALWAYS: Will always generate the assets & will be stored in memory. There will be no cache folder
	#Allowed Values: NEVER, RUN_ONCE, CACHED, CACHED_ZIPPED, ALWAYS
	dynamic_assets_generation_mode = "ALWAYS"
	#Enable Every-Compat to base textures off external Resource Packs rather than mod's default textures.
	#ATTENTION: There are some Resource Packs that won't work well with Every-Compat, which is why this
	#option is off by default. Disable if there are missing textures for blocks.
	#
	use_external_resource_pack = false
