		[types.wood_type.nomansland]
			pine = true
			maple = true
			walnut = true
			willow = true

		[types.leaves_type.nomansland]
			autumnal_oak = true
			frosted = true
			pale_cherry = true
			red_maple = true
			yellow_birch = true
			pine = true
			maple = true
			walnut = true
			willow = true
			apple_fruit = true
			pear_fruit = true

		[entries.wood_type.another_furniture]
			drawer = true
			table = true
			flower_box = true
			shelf = true
			shutter = true
			bench = true
			chair = true

		[entries.wood_type.create]
			window_pane = true
			window = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.nomansland]
			bookshelf = true
			trimmed_planks = true
