#For configuring the mob remodels, go to the mixed litter startup config!
[tortoise_shell_attributes]
	#The attributes of the tortoise shell armor item
	# Default: 670
	# Range: > -2147483648
	durability = 670
	# Default: 4
	# Range: > -2147483648
	armor = 4
	# Default: 3.0
	# Range: -100.0 ~ 100.0
	toughness = 3.0
	# Default: -0.3
	# Range: -100.0 ~ 100.0
	speedReduction = -0.3
	# Default: 0.2
	# Range: -100.0 ~ 100.0
	knockbackResistance = 0.2
