	[ui.colors]
		#Color of the book text. Default: FF7B593D
		text_color = "FF7B593D"
		#Color of the page numbers. Default: FFEFE4CA
		page_numbers_color = "FFEFE4CA"
		#Color of the 'Enter Book Title' text in the signing screen. Default: FFF5EBD0
		enter_title_color = "FFF5EBD0"
		#Color of the 'by <author>' text in the signing screen. Default: FFC7B496
		by_author_color = "FFC7B496"
		#Color of the selection. Default: FF664488
		selection_color = "FF664488"
		#Color of the selection when text box is not focused. Default: FF827B88
		selection_unfocused_color = "FF827B88"

#Settings in this category are automatically updated by the mod itself. You don't need to change them, unless the desire is irresistible.
[tutorial]
	#Extra tools button is flashing red to grab attention until the player toggles it.
	extra_tools = true
